package QuanLyGiangVien.GUI;

import Controller.DanhMucBean;
import Controller.ChuyenManHinh;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author Admin
 */
public class MainJFrame extends javax.swing.JFrame {
    public MainJFrame() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        setTitle("QUẢN LÝ GIẢNG VIÊN");
        
        ChuyenManHinh controller = new ChuyenManHinh(jpnView);
        controller.setView(jpnGiangVien, jlbTrangChu);
        
        List<DanhMucBean> listItem = new ArrayList<>();
        listItem.add(new DanhMucBean("TrangChu", jlbTrangChu, jpnTrangChu));
        listItem.add(new DanhMucBean("GiangVien", jlbGiangVien, jpnGiangVien));
        listItem.add(new DanhMucBean("Khoa", jlbKhoa, jpnKhoa));
        listItem.add(new DanhMucBean("LichDay", jlbLichDay, jpnLichDay));
        listItem.add(new DanhMucBean("NCKH", jlbNCKH, jpnNCKH));
        listItem.add(new DanhMucBean("HoatDong", jlbHoatDong, jpnHoatDong));
        listItem.add(new DanhMucBean("PhanQuyen", jlbPhanQuyen, jpnPhanQuyen));
        listItem.add(new DanhMucBean("TaiKhoan", jlbTaiKhoan, jpnTaiKhoan));
        
        
        controller.setEvent(listItem);
    }   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnRoot = new javax.swing.JPanel();
        jpnView = new javax.swing.JPanel();
        jpnMenu = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jpnLichDay = new javax.swing.JPanel();
        jlbLichDay = new javax.swing.JLabel();
        jpnTaiKhoan = new javax.swing.JPanel();
        jlbTaiKhoan = new javax.swing.JLabel();
        jpnNCKH = new javax.swing.JPanel();
        jlbNCKH = new javax.swing.JLabel();
        jpnHoatDong = new javax.swing.JPanel();
        jlbHoatDong = new javax.swing.JLabel();
        jpnTrangChu = new javax.swing.JPanel();
        jlbTrangChu = new javax.swing.JLabel();
        jpnGiangVien = new javax.swing.JPanel();
        jlbGiangVien = new javax.swing.JLabel();
        jpnKhoa = new javax.swing.JPanel();
        jlbKhoa = new javax.swing.JLabel();
        jpnPhanQuyen = new javax.swing.JPanel();
        jlbPhanQuyen = new javax.swing.JLabel();
        jpnDangXuat = new javax.swing.JPanel();
        jlbDangXuat = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(96, 222, 222));

        jpnRoot.setBackground(new java.awt.Color(255, 255, 255));
        jpnRoot.setForeground(new java.awt.Color(255, 255, 255));
        jpnRoot.setPreferredSize(new java.awt.Dimension(1350, 700));

        jpnView.setBackground(new java.awt.Color(255, 255, 255));
        jpnView.setPreferredSize(new java.awt.Dimension(800, 800));

        javax.swing.GroupLayout jpnViewLayout = new javax.swing.GroupLayout(jpnView);
        jpnView.setLayout(jpnViewLayout);
        jpnViewLayout.setHorizontalGroup(
            jpnViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1352, Short.MAX_VALUE)
        );
        jpnViewLayout.setVerticalGroup(
            jpnViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jpnRootLayout = new javax.swing.GroupLayout(jpnRoot);
        jpnRoot.setLayout(jpnRootLayout);
        jpnRootLayout.setHorizontalGroup(
            jpnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnRootLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jpnView, javax.swing.GroupLayout.PREFERRED_SIZE, 1352, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jpnRootLayout.setVerticalGroup(
            jpnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnView, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
        );

        jpnMenu.setBackground(new java.awt.Color(28, 38, 45));
        jpnMenu.setForeground(new java.awt.Color(255, 255, 255));
        jpnMenu.setPreferredSize(new java.awt.Dimension(300, 872));
        jpnMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(28, 38, 45));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/sgu.png"))); // NOI18N
        jLabel1.setText("SGU University");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 37, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jpnMenu.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, -1));

        jpnLichDay.setBackground(new java.awt.Color(28, 38, 45));
        jpnLichDay.setForeground(new java.awt.Color(28, 38, 45));

        jlbLichDay.setFont(new java.awt.Font("Times New Roman", 0, 25)); // NOI18N
        jlbLichDay.setForeground(new java.awt.Color(255, 255, 255));
        jlbLichDay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/lich.png"))); // NOI18N
        jlbLichDay.setText("Lịch dạy");

        javax.swing.GroupLayout jpnLichDayLayout = new javax.swing.GroupLayout(jpnLichDay);
        jpnLichDay.setLayout(jpnLichDayLayout);
        jpnLichDayLayout.setHorizontalGroup(
            jpnLichDayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnLichDayLayout.createSequentialGroup()
                .addComponent(jlbLichDay, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 69, Short.MAX_VALUE))
        );
        jpnLichDayLayout.setVerticalGroup(
            jpnLichDayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnLichDayLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbLichDay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jpnMenu.add(jpnLichDay, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 220, 70));

        jpnTaiKhoan.setBackground(new java.awt.Color(28, 38, 45));
        jpnTaiKhoan.setForeground(new java.awt.Color(28, 38, 45));

        jlbTaiKhoan.setFont(new java.awt.Font("Times New Roman", 0, 25)); // NOI18N
        jlbTaiKhoan.setForeground(new java.awt.Color(255, 255, 255));
        jlbTaiKhoan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/tk.png"))); // NOI18N
        jlbTaiKhoan.setText("Tài khoản");

        javax.swing.GroupLayout jpnTaiKhoanLayout = new javax.swing.GroupLayout(jpnTaiKhoan);
        jpnTaiKhoan.setLayout(jpnTaiKhoanLayout);
        jpnTaiKhoanLayout.setHorizontalGroup(
            jpnTaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnTaiKhoanLayout.createSequentialGroup()
                .addComponent(jlbTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 50, Short.MAX_VALUE))
        );
        jpnTaiKhoanLayout.setVerticalGroup(
            jpnTaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnTaiKhoanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbTaiKhoan)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jpnMenu.add(jpnTaiKhoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 570, 190, 70));

        jpnNCKH.setBackground(new java.awt.Color(28, 38, 45));
        jpnNCKH.setForeground(new java.awt.Color(28, 38, 45));

        jlbNCKH.setFont(new java.awt.Font("Times New Roman", 0, 25)); // NOI18N
        jlbNCKH.setForeground(new java.awt.Color(255, 255, 255));
        jlbNCKH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/nckh.png"))); // NOI18N
        jlbNCKH.setText("Nghiên cứu khoa học");

        javax.swing.GroupLayout jpnNCKHLayout = new javax.swing.GroupLayout(jpnNCKH);
        jpnNCKH.setLayout(jpnNCKHLayout);
        jpnNCKHLayout.setHorizontalGroup(
            jpnNCKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnNCKHLayout.createSequentialGroup()
                .addComponent(jlbNCKH, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 38, Short.MAX_VALUE))
        );
        jpnNCKHLayout.setVerticalGroup(
            jpnNCKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnNCKHLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jlbNCKH, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        jpnMenu.add(jpnNCKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 290, 90));

        jpnHoatDong.setBackground(new java.awt.Color(28, 38, 45));
        jpnHoatDong.setForeground(new java.awt.Color(28, 38, 45));

        jlbHoatDong.setFont(new java.awt.Font("Times New Roman", 0, 25)); // NOI18N
        jlbHoatDong.setForeground(new java.awt.Color(255, 255, 255));
        jlbHoatDong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/hoatdong.png"))); // NOI18N
        jlbHoatDong.setText("Hoạt động");

        javax.swing.GroupLayout jpnHoatDongLayout = new javax.swing.GroupLayout(jpnHoatDong);
        jpnHoatDong.setLayout(jpnHoatDongLayout);
        jpnHoatDongLayout.setHorizontalGroup(
            jpnHoatDongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnHoatDongLayout.createSequentialGroup()
                .addComponent(jlbHoatDong)
                .addGap(0, 49, Short.MAX_VALUE))
        );
        jpnHoatDongLayout.setVerticalGroup(
            jpnHoatDongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnHoatDongLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jlbHoatDong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(49, 49, 49))
        );

        jpnMenu.add(jpnHoatDong, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 180, 80));

        jpnTrangChu.setBackground(new java.awt.Color(28, 38, 45));
        jpnTrangChu.setForeground(new java.awt.Color(28, 38, 45));

        jlbTrangChu.setFont(new java.awt.Font("Times New Roman", 0, 25)); // NOI18N
        jlbTrangChu.setForeground(new java.awt.Color(255, 255, 255));
        jlbTrangChu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/trangchu.png"))); // NOI18N
        jlbTrangChu.setText("Trang chủ");

        javax.swing.GroupLayout jpnTrangChuLayout = new javax.swing.GroupLayout(jpnTrangChu);
        jpnTrangChu.setLayout(jpnTrangChuLayout);
        jpnTrangChuLayout.setHorizontalGroup(
            jpnTrangChuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnTrangChuLayout.createSequentialGroup()
                .addComponent(jlbTrangChu, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 95, Short.MAX_VALUE))
        );
        jpnTrangChuLayout.setVerticalGroup(
            jpnTrangChuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnTrangChuLayout.createSequentialGroup()
                .addGap(0, 16, Short.MAX_VALUE)
                .addComponent(jlbTrangChu, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jpnMenu.add(jpnTrangChu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 230, 60));

        jpnGiangVien.setBackground(new java.awt.Color(28, 38, 45));
        jpnGiangVien.setForeground(new java.awt.Color(28, 38, 45));

        jlbGiangVien.setFont(new java.awt.Font("Times New Roman", 0, 25)); // NOI18N
        jlbGiangVien.setForeground(new java.awt.Color(255, 255, 255));
        jlbGiangVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/gv.png"))); // NOI18N
        jlbGiangVien.setText("Giảng viên");

        javax.swing.GroupLayout jpnGiangVienLayout = new javax.swing.GroupLayout(jpnGiangVien);
        jpnGiangVien.setLayout(jpnGiangVienLayout);
        jpnGiangVienLayout.setHorizontalGroup(
            jpnGiangVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnGiangVienLayout.createSequentialGroup()
                .addComponent(jlbGiangVien)
                .addGap(0, 83, Short.MAX_VALUE))
        );
        jpnGiangVienLayout.setVerticalGroup(
            jpnGiangVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnGiangVienLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jlbGiangVien, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        jpnMenu.add(jpnGiangVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 220, 70));

        jpnKhoa.setBackground(new java.awt.Color(28, 38, 45));
        jpnKhoa.setForeground(new java.awt.Color(28, 38, 45));

        jlbKhoa.setFont(new java.awt.Font("Times New Roman", 0, 25)); // NOI18N
        jlbKhoa.setForeground(new java.awt.Color(255, 255, 255));
        jlbKhoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/gv.png"))); // NOI18N
        jlbKhoa.setText("Khoa");

        javax.swing.GroupLayout jpnKhoaLayout = new javax.swing.GroupLayout(jpnKhoa);
        jpnKhoa.setLayout(jpnKhoaLayout);
        jpnKhoaLayout.setHorizontalGroup(
            jpnKhoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnKhoaLayout.createSequentialGroup()
                .addComponent(jlbKhoa)
                .addGap(0, 139, Short.MAX_VALUE))
        );
        jpnKhoaLayout.setVerticalGroup(
            jpnKhoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnKhoaLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jlbKhoa, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jpnMenu.add(jpnKhoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, -1, 80));

        jpnPhanQuyen.setBackground(new java.awt.Color(28, 38, 45));
        jpnPhanQuyen.setForeground(new java.awt.Color(28, 38, 45));

        jlbPhanQuyen.setFont(new java.awt.Font("Times New Roman", 0, 25)); // NOI18N
        jlbPhanQuyen.setForeground(new java.awt.Color(255, 255, 255));
        jlbPhanQuyen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/hoatdong.png"))); // NOI18N
        jlbPhanQuyen.setText("Phân Quyền");

        javax.swing.GroupLayout jpnPhanQuyenLayout = new javax.swing.GroupLayout(jpnPhanQuyen);
        jpnPhanQuyen.setLayout(jpnPhanQuyenLayout);
        jpnPhanQuyenLayout.setHorizontalGroup(
            jpnPhanQuyenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnPhanQuyenLayout.createSequentialGroup()
                .addComponent(jlbPhanQuyen)
                .addGap(0, 49, Short.MAX_VALUE))
        );
        jpnPhanQuyenLayout.setVerticalGroup(
            jpnPhanQuyenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnPhanQuyenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbPhanQuyen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(61, 61, 61))
        );

        jpnMenu.add(jpnPhanQuyen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, -1, 80));

        jpnDangXuat.setBackground(new java.awt.Color(28, 38, 45));
        jpnDangXuat.setForeground(new java.awt.Color(28, 38, 45));

        jlbDangXuat.setFont(new java.awt.Font("Times New Roman", 0, 25)); // NOI18N
        jlbDangXuat.setForeground(new java.awt.Color(255, 255, 255));
        jlbDangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/tk.png"))); // NOI18N
        jlbDangXuat.setText("Đăng Xuất");

        javax.swing.GroupLayout jpnDangXuatLayout = new javax.swing.GroupLayout(jpnDangXuat);
        jpnDangXuat.setLayout(jpnDangXuatLayout);
        jpnDangXuatLayout.setHorizontalGroup(
            jpnDangXuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnDangXuatLayout.createSequentialGroup()
                .addComponent(jlbDangXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 50, Short.MAX_VALUE))
        );
        jpnDangXuatLayout.setVerticalGroup(
            jpnDangXuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnDangXuatLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jlbDangXuat)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jpnMenu.add(jpnDangXuat, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 630, -1, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnRoot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnRoot, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
            .addComponent(jpnMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel jlbDangXuat;
    private javax.swing.JLabel jlbGiangVien;
    private javax.swing.JLabel jlbHoatDong;
    private javax.swing.JLabel jlbKhoa;
    private javax.swing.JLabel jlbLichDay;
    private javax.swing.JLabel jlbNCKH;
    private javax.swing.JLabel jlbPhanQuyen;
    private javax.swing.JLabel jlbTaiKhoan;
    private javax.swing.JLabel jlbTrangChu;
    private javax.swing.JPanel jpnDangXuat;
    private javax.swing.JPanel jpnGiangVien;
    private javax.swing.JPanel jpnHoatDong;
    private javax.swing.JPanel jpnKhoa;
    private javax.swing.JPanel jpnLichDay;
    private javax.swing.JPanel jpnMenu;
    private javax.swing.JPanel jpnNCKH;
    private javax.swing.JPanel jpnPhanQuyen;
    private javax.swing.JPanel jpnRoot;
    private javax.swing.JPanel jpnTaiKhoan;
    private javax.swing.JPanel jpnTrangChu;
    private javax.swing.JPanel jpnView;
    // End of variables declaration//GEN-END:variables
}
