package QuanLyGiangVien.GUI;

import Controller.DanhMucBean;
import Controller.ChuyenManHinh;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author Admin
 */
public class MainJFrame extends javax.swing.JFrame {
    public MainJFrame() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        setTitle("QUẢN LÝ GIẢNG VIÊN");
        
        ChuyenManHinh controller = new ChuyenManHinh(jpnView);
        controller.setView(jpnGiangVien, jlbTrangChu);
        
        List<DanhMucBean> listItem = new ArrayList<>();
        listItem.add(new DanhMucBean("TrangChu", jlbTrangChu, jpnTrangChu));
        listItem.add(new DanhMucBean("GiangVien", jlbGiangVien, jpnGiangVien));
        listItem.add(new DanhMucBean("NCKH", jlbNCKH, jpnNCKH));
        listItem.add(new DanhMucBean("HoatDong", jlbHoatDong, jpnHoatDong));
        listItem.add(new DanhMucBean("LichDay", jlbLichDay, jpnLichDay));
        listItem.add(new DanhMucBean("TaiKhoan", jlbTaiKhoan, jpnTaiKhoan));
        
        
        controller.setEvent(listItem);
    }   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnRoot = new javax.swing.JPanel();
        jpnMenu = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jpnLichDay = new javax.swing.JPanel();
        jlbLichDay = new javax.swing.JLabel();
        jpnTaiKhoan = new javax.swing.JPanel();
        jlbTaiKhoan = new javax.swing.JLabel();
        jpnNCKH = new javax.swing.JPanel();
        jlbNCKH = new javax.swing.JLabel();
        jpnHoatDong = new javax.swing.JPanel();
        jlbHoatDong = new javax.swing.JLabel();
        jpnTrangChu = new javax.swing.JPanel();
        jlbTrangChu = new javax.swing.JLabel();
        jpnGiangVien = new javax.swing.JPanel();
        jlbGiangVien = new javax.swing.JLabel();
        jpnView = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(96, 222, 222));
        setPreferredSize(new java.awt.Dimension(1362, 850));

        jpnRoot.setBackground(new java.awt.Color(255, 255, 255));
        jpnRoot.setForeground(new java.awt.Color(255, 255, 255));
        jpnRoot.setPreferredSize(new java.awt.Dimension(1350, 700));

        jpnMenu.setBackground(new java.awt.Color(102, 204, 204));
        jpnMenu.setForeground(new java.awt.Color(255, 255, 255));
        jpnMenu.setPreferredSize(new java.awt.Dimension(300, 872));
        jpnMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(102, 204, 204));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/sgu.png"))); // NOI18N
        jLabel1.setText("SGU University");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        jpnMenu.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, -1));

        jpnLichDay.setBackground(new java.awt.Color(102, 204, 204));

        jlbLichDay.setFont(new java.awt.Font("Times New Roman", 0, 25)); // NOI18N
        jlbLichDay.setForeground(new java.awt.Color(255, 255, 255));
        jlbLichDay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/lich.png"))); // NOI18N
        jlbLichDay.setText("Lịch dạy");

        javax.swing.GroupLayout jpnLichDayLayout = new javax.swing.GroupLayout(jpnLichDay);
        jpnLichDay.setLayout(jpnLichDayLayout);
        jpnLichDayLayout.setHorizontalGroup(
            jpnLichDayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnLichDayLayout.createSequentialGroup()
                .addContainerGap(85, Short.MAX_VALUE)
                .addComponent(jlbLichDay, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
        );
        jpnLichDayLayout.setVerticalGroup(
            jpnLichDayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnLichDayLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jlbLichDay, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );

        jpnMenu.add(jpnLichDay, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, 300, 100));

        jpnTaiKhoan.setBackground(new java.awt.Color(102, 204, 204));

        jlbTaiKhoan.setFont(new java.awt.Font("Times New Roman", 0, 25)); // NOI18N
        jlbTaiKhoan.setForeground(new java.awt.Color(255, 255, 255));
        jlbTaiKhoan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/tk.png"))); // NOI18N
        jlbTaiKhoan.setText("Tài khoản");

        javax.swing.GroupLayout jpnTaiKhoanLayout = new javax.swing.GroupLayout(jpnTaiKhoan);
        jpnTaiKhoan.setLayout(jpnTaiKhoanLayout);
        jpnTaiKhoanLayout.setHorizontalGroup(
            jpnTaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnTaiKhoanLayout.createSequentialGroup()
                .addContainerGap(91, Short.MAX_VALUE)
                .addComponent(jlbTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69))
        );
        jpnTaiKhoanLayout.setVerticalGroup(
            jpnTaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnTaiKhoanLayout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addComponent(jlbTaiKhoan)
                .addGap(22, 22, 22))
        );

        jpnMenu.add(jpnTaiKhoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 630, 300, 90));

        jpnNCKH.setBackground(new java.awt.Color(102, 204, 204));
        jpnNCKH.setForeground(new java.awt.Color(102, 204, 204));

        jlbNCKH.setFont(new java.awt.Font("Times New Roman", 0, 25)); // NOI18N
        jlbNCKH.setForeground(new java.awt.Color(255, 255, 255));
        jlbNCKH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/nckh.png"))); // NOI18N
        jlbNCKH.setText("Nghiên cứu khoa học");

        javax.swing.GroupLayout jpnNCKHLayout = new javax.swing.GroupLayout(jpnNCKH);
        jpnNCKH.setLayout(jpnNCKHLayout);
        jpnNCKHLayout.setHorizontalGroup(
            jpnNCKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnNCKHLayout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jlbNCKH, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        jpnNCKHLayout.setVerticalGroup(
            jpnNCKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnNCKHLayout.createSequentialGroup()
                .addComponent(jlbNCKH, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jpnMenu.add(jpnNCKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 313, 300, 90));

        jpnHoatDong.setBackground(new java.awt.Color(102, 204, 204));

        jlbHoatDong.setFont(new java.awt.Font("Times New Roman", 0, 25)); // NOI18N
        jlbHoatDong.setForeground(new java.awt.Color(255, 255, 255));
        jlbHoatDong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/hoatdong.png"))); // NOI18N
        jlbHoatDong.setText("Hoạt động");

        javax.swing.GroupLayout jpnHoatDongLayout = new javax.swing.GroupLayout(jpnHoatDong);
        jpnHoatDong.setLayout(jpnHoatDongLayout);
        jpnHoatDongLayout.setHorizontalGroup(
            jpnHoatDongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnHoatDongLayout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(jlbHoatDong)
                .addContainerGap(84, Short.MAX_VALUE))
        );
        jpnHoatDongLayout.setVerticalGroup(
            jpnHoatDongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnHoatDongLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jlbHoatDong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(29, 29, 29))
        );

        jpnMenu.add(jpnHoatDong, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 300, -1));

        jpnTrangChu.setBackground(new java.awt.Color(102, 204, 204));
        jpnTrangChu.setForeground(new java.awt.Color(102, 204, 204));

        jlbTrangChu.setFont(new java.awt.Font("Times New Roman", 0, 25)); // NOI18N
        jlbTrangChu.setForeground(new java.awt.Color(255, 255, 255));
        jlbTrangChu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/trangchu.png"))); // NOI18N
        jlbTrangChu.setText("Trang chủ");

        javax.swing.GroupLayout jpnTrangChuLayout = new javax.swing.GroupLayout(jpnTrangChu);
        jpnTrangChu.setLayout(jpnTrangChuLayout);
        jpnTrangChuLayout.setHorizontalGroup(
            jpnTrangChuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnTrangChuLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(jlbTrangChu, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(92, Short.MAX_VALUE))
        );
        jpnTrangChuLayout.setVerticalGroup(
            jpnTrangChuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnTrangChuLayout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addComponent(jlbTrangChu, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jpnMenu.add(jpnTrangChu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 300, -1));

        jpnGiangVien.setBackground(new java.awt.Color(102, 204, 204));
        jpnGiangVien.setForeground(new java.awt.Color(102, 204, 204));

        jlbGiangVien.setFont(new java.awt.Font("Times New Roman", 0, 25)); // NOI18N
        jlbGiangVien.setForeground(new java.awt.Color(255, 255, 255));
        jlbGiangVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/gv.png"))); // NOI18N
        jlbGiangVien.setText("Giảng viên");

        javax.swing.GroupLayout jpnGiangVienLayout = new javax.swing.GroupLayout(jpnGiangVien);
        jpnGiangVien.setLayout(jpnGiangVienLayout);
        jpnGiangVienLayout.setHorizontalGroup(
            jpnGiangVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnGiangVienLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(jlbGiangVien)
                .addContainerGap(87, Short.MAX_VALUE))
        );
        jpnGiangVienLayout.setVerticalGroup(
            jpnGiangVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnGiangVienLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jlbGiangVien, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        jpnMenu.add(jpnGiangVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 218, 300, 90));

        jpnView.setBackground(new java.awt.Color(255, 255, 255));
        jpnView.setPreferredSize(new java.awt.Dimension(800, 800));

        javax.swing.GroupLayout jpnViewLayout = new javax.swing.GroupLayout(jpnView);
        jpnView.setLayout(jpnViewLayout);
        jpnViewLayout.setHorizontalGroup(
            jpnViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1054, Short.MAX_VALUE)
        );
        jpnViewLayout.setVerticalGroup(
            jpnViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 850, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jpnRootLayout = new javax.swing.GroupLayout(jpnRoot);
        jpnRoot.setLayout(jpnRootLayout);
        jpnRootLayout.setHorizontalGroup(
            jpnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnRootLayout.createSequentialGroup()
                .addComponent(jpnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jpnView, javax.swing.GroupLayout.PREFERRED_SIZE, 1054, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jpnRootLayout.setVerticalGroup(
            jpnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 850, Short.MAX_VALUE)
            .addComponent(jpnView, javax.swing.GroupLayout.DEFAULT_SIZE, 850, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpnRoot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnRoot, javax.swing.GroupLayout.DEFAULT_SIZE, 850, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel jlbGiangVien;
    private javax.swing.JLabel jlbHoatDong;
    private javax.swing.JLabel jlbLichDay;
    private javax.swing.JLabel jlbNCKH;
    private javax.swing.JLabel jlbTaiKhoan;
    private javax.swing.JLabel jlbTrangChu;
    private javax.swing.JPanel jpnGiangVien;
    private javax.swing.JPanel jpnHoatDong;
    private javax.swing.JPanel jpnLichDay;
    private javax.swing.JPanel jpnMenu;
    private javax.swing.JPanel jpnNCKH;
    private javax.swing.JPanel jpnRoot;
    private javax.swing.JPanel jpnTaiKhoan;
    private javax.swing.JPanel jpnTrangChu;
    private javax.swing.JPanel jpnView;
    // End of variables declaration//GEN-END:variables
}
